Controllers/HomeController.cs
using System.Collections.Generic;
using Mandee.Models;
using Microsoft.AspNetCore.Http;  
using Microsoft.AspNetCore.Mvc; 

namespace Mandee.Controllers
{
	public class HomeController : Controller
	{
		const string LoggedUserID = "_Logged";
		const string UserID = "_ID";

		[HttpGet]
	    public IActionResult Index()
		{
		    /*
            * Assign page title with view bag, create a model and pass to view
            */
		    ViewBag.title = "Welcome";
		    List<Models.AdModel> modelList = Domain.ContentCreation.CreationUtilties.MakeCaseStudies();
		    return View(modelList);
		}

	    [HttpGet]
	    public IActionResult RegistrationForm()
	    {
	        /*
            * Assign page title with view bag
            */
	        ViewBag.title = "Registration";
	        return View();
	    }

	    [HttpPost]
	    public IActionResult RegistrationForm(RegModel registration)
	    {
            /*
            * Assign page title with view bag, check returned model is valid
            * if true pass model to completed view if false return to view
            */
	        ViewBag.title = "Registration required";
	        if (ModelState.IsValid)
	        {
	            return View("Completed", registration);
	        }
	        else
	        {
	            return View();
	        }
	    }

	    [HttpGet]
	    public IActionResult LoginForm()
	    {
	        /*
            * Assign page title with view bag
            */
	        ViewBag.title = "Login";
	        return View();
	    }

	    [HttpPost]
	    [ValidateAntiForgeryToken]
	    public IActionResult LoginForm(UserModel user)
	    {
	        /*
            * Check if model properties are set and then set session variable.
            * Allow session status to be passed between pages using tempData
            * Assign page title with view bag, check returned model is valid
            * if true pass model to secure view if false return to view
            */
	        ViewBag.title = "Login";
	        if (ModelState.IsValid)
	        {
	            if (!((user.Password != null) & (user.Email != null))) return View(user);
	            var UserList = new UserModel(){Password = "pass", Email = "demo@demo.com"};
				HttpContext.Session.SetString(LoggedUserID, UserList.Email.ToString());
	            TempData["UserID"] = HttpContext.Session.GetString(LoggedUserID);
	            //return RedirectToAction("Secure");
	            return Redirect(Url.RouteUrl(new { controller = "Home", action = "Secure" }) + "#anchor");
	        }
	        else
	        {
	            return View();
	        }
	    }

	    [HttpGet]
	    public IActionResult Completed()
	    {
	        /*
            * Assign page title with view bag
            */
	        ViewBag.title = "Thank you";
	        return View();
	    }

	    [HttpGet]
	    public IActionResult Secure()
	    {
	        /*
            * Assign page title with view bag
            * Check session status and return view
            * If navigate away then null TempData and force a re-login
            */
	        ViewBag.title = "Restricted Area";
	        if (HttpContext.Session.GetString(LoggedUserID) != null && TempData["UserID"] != null )
	        {
	            return View();
	        }
	        TempData["UserID"] = null;
	        return RedirectToAction("LoginForm", "Home");
	    }

	    [HttpGet]
	        /*
            * create a model and pass to partial model
            */
	    public IActionResult TeamPartial()
	    {
	        List<TeamModel> modelList = Domain.ContentCreation.CreationUtilties.MakeTeam();
	        return PartialView("Shared/_TeamPartial",modelList);
	    }
	}
}

Controllers/InterviewController.cs
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Mandee.Models;

namespace Mandee.Controllers
{
    public class InterviewController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            /*
            * Assign page title with view bag
            */
            ViewBag.title = "Interview request";
            return View();
        }

        [HttpGet]
        public IActionResult InterviewForm()
        {
            /*
            * Assign page title with view bag
            */
            ViewBag.title = "Interview request";
            return View();
        }

        [HttpPost]
        public IActionResult InterviewForm(VacancyApplyModel vacancy)
        {
            /*
            * Assign page title with view bag
            * Check model is correct or act accordingly
            */
            ViewBag.title = "Interview request";
            if (ModelState.IsValid)
            {
                ViewBag.title = "Interview form";
                return View("ThankYou", vacancy);
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult ThankYou()
        {
            /*
            * Assign page title with view bag
            */
            ViewBag.title = "Thankyou";
            return View();
        }
    }
}

Views/Home/Completed.cshtml
@model Mandee.Models.RegModel

<div>
    <h1>Congratualation, @Model.Name!!!</h1>
        <p>Your Registration has been Successfully completed.</p>
    </div>

Views/Home/Index.cshtml
@using Mandee.Domain.ContentCreation
@using Mandee.Models
@model List<AdModel>

<div class="container-fluid">
    <!-- -------------------------------------------Circle scroll row--------------------------------------------------- -->
    <div class="row">
        <div id="circle">
            <a id="misc" href="#misc">
                <i class="fa fa-arrow-down fa-3x" aria-hidden="true"></i>
            </a>
        </div>
    </div>
    <!-- -----------------------------------------------Header row------------------------------------------------------- -->
    <div class="row">
        <div class="HomeHeader col p-5" style="margin-top: -48px;  min-height: 400px; width: 100%; background-color: ghostwhite">
            <h2 class="h2 text-center">
                Introduction
            </h2>
            <br />
            <p>I’m a <span class="red">creative</span> award-winning internal communications professional, specialising in employee engagement, using business partnering teamed with people-focused storytelling to build vibrant internal communities.</p>
            <br />
            <p>Helping leaders find ways of making their people care about meeting their business objective. I use a coaching and collaborative approach that empowers employees as brand ambassadors and communicators.</p>
            <br />
            <p>I have over six years experience in organisational change, channel development, creating content and producing films and in events management. I get things done.</p>
        </div>
    </div>
    <!-- -----------------------------------------------Case studies row------------------------------------------------------- -->
    <div class="row">
        <div class="HomeCaseStudies scrolltarget">

            <h2 class="h2 text-center py-5" style="color: ghostwhite;">
                Case Studies
            </h2>

            <div id="card-list" class="row px-5 pb-5">
                @{
                    foreach (var getter in Model)
                    {
                        <div class="col-lg-4 col-md-6 my-1">
                            <div class="card">
                                <div class="card-header">
                                    @getter.Title
                                </div>
                                <div class="card-block">
                                    <h4 class="card-title">Case study details:</h4>
                                    <p class="card-text">@getter.Description</p>
                                    <a href="@Url.Action("FindOutMore", "CaseStudies", new {@Title = getter.Title, @Author = getter.Author, @Description = getter.Description, @Url = getter.Url})" class="btn btn-primary pull-right">Find out more</a>
                                </div>
                                <div class="card-footer text-muted">
                                    <p style="font-size: 0.7em; font-style: italic">Submitted by: @getter.Author closing date: @getter.EndAd.ToShortDateString()</p>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
    <!-- ----------------------------------------------Social media row------------------------------------------------------ -->
    <div class="row">
        <div class="HomeSocialMedia col pb-5 px-5" style="padding-top: 60px; min-height: 400px; width: 100%; background-color: ghostwhite">
            <h2 class="h2 text-center">
                Social media
            </h2>
            <br />
            <p>
                Nulla ut sollicitudin ipsum, eget feugiat tortor. Sed eget eleifend odio. Sed sit amet pretium urna. Nullam non nisl mi.
            </p>
            <p>
                Sed feugiat tincidunt massa id vulputate. Morbi rutrum purus suscipit, pretium felis vel, vulputate velit. Etiam sed urna dolor. Sed consequat quam est, et sagittis purus eleifend sed. Sed a.
            </p>
            <br />
            <div class="text-center">
                <a href="#"> <i class="fa fa-facebook-official fa-5x" aria-hidden="true"></i></a>
                <a href="#"> <i class="fa fa-twitter-square fa-5x" aria-hidden="true"></i></a>
                <a href="#"> <i class="fa fa-instagram fa-5x" aria-hidden="true"></i></a>
                <a href="#"> <i class="fa fa-linkedin-square fa-5x" aria-hidden="true"></i></a>
            </div>
        </div>
    </div>
    <!-- -----------------------------------------------Video examples------------------------------------------------------- -->
    <div class="row">
        <div class="HomeTeam" style="min-height: 400px; width: 100%; background-color: #292b2c">

            <h2 class="h2 text-center py-5" style="color: ghostwhite;">
                Something I made earlier
            </h2>
            @Html.Partial("~/Views/Home/Shared/_TeamPartial.cshtml", CreationUtilties.MakeTeam())
        </div>
    </div>
    <!-- ------------------------------------------------------------------------------------------------------------------------>
    <div class="row">
        <div class="HomeExperience col p-5">
            <h2 class="h2 text-center py-5">
                Experience
            </h2>
            <br />
            <p>
                Over 16 years experience working on the East Coast Mainline working in
                the Travel Centre, Customer Relations, Retail Accounts and in the
                Communication teams
            </p>
            <p>
                During this time, I managed the rollout and development of an intranet
                site, ezine, newspaper, magazine and Yammer. I’ve run the employee
                awards for six years, launched three new uniform launches, and
                produced, scripted and directed all our employee films, organised filming
                with the BBC and ITV for external events, and I helped source stories,
                employees for the 2014 documentary ‘All Aboard East Coast Trains’
            </p>
        </div>
    </div>
    <!-- ----------------------------------------------Contact row------------------------------------------------------ -->
    <div class="row">
        <div class="Interview col pb-5 px-5" style="padding-top: 60px; min-height: 400px; width: 100%;  background-color: ghostwhite">
            <h2 class="h2 text-center">
                Contact
            </h2>
            <br />
            <p>
                Nulla ut sollicitudin ipsum, eget feugiat tortor. Sed eget eleifend odio. Sed sit amet pretium urna. Nullam non nisl mi.
            </p>
            <p>
                Sed feugiat tincidunt massa id vulputate. Morbi rutrum purus suscipit, pretium felis vel, vulputate velit. Etiam sed urna dolor. Sed consequat quam est, et sagittis purus eleifend sed. Sed a.
            </p>
            <br />
            <div class="card">
                <h3 class="card-header">Request a consultation</h3>
                <div class="card-block">
                    <h4 class="card-title">Want a professional boost to your job search?</h4>
                    <p class="card-text">Quisque blandit interdum tortor, vitae mollis purus. Proin condimentum facilisis dolor, quis ornare est ultrices a. Sed ut elementum est. Vestibulum quis tellus sed dui scelerisque tincidunt in id urna.</p>
                    @Html.ActionLink("Book a call", "InterviewForm", "Interview", null, null, "anchor", null, new { @class = "btn btn-primary pull-right" })
                </div>
            </div>
        </div>
    </div>
</div>
<iframe id="chat" src='' style='position:fixed;min-width: 200px; width: 30%; min-height: 300px; bottom: 0px; right: 0px; z-index:999;background-color:white'></iframe>
@section Scripts {
    <script src="~/Content/JS/centreItHomePage.js"></script>
    <script>
        var xhr = new XMLHttpRequest();
        xhr.open('GET', "https://webchat.botframework.com/api/tokens", true);
        xhr.setRequestHeader('Authorization', 'BotConnector ' + '6sCzkESlABQ.BNMOcCFK6n5BLLeZb9ICeY-OHG1e2Y1Pndt9ZaQpUE4');
        xhr.send();
        xhr.onreadystatechange = processRequest;

        function processRequest(e) {
            if (xhr.readyState == 4 && xhr.status == 200) {
                var response = JSON.parse(xhr.responseText);
                document.getElementById("chat").src = "https://webchat.botframework.com/embed/DrewBotTest?t=" + response
            }
        }
    </script>
}

Views/Home/LoginForm.cshtml
@model Mandee.Models.UserModel
<div class="container">
    <div class="row pb-5">
        <div class="col">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-signin">
                    <h2 class="form-signin-heading" id="anchor">Login</h2>
                    <div>
                        @Html.LabelFor(x => x.Email, new {@class = "sr-only"})
                        @Html.TextBoxFor(x => x.Email, new {id = "inputEmail", @class = "form-control", placeholder = "Email address"})
                        @Html.ValidationMessageFor(x => x.Email, null, new {id = "l-Style", style = "color:#FF1C4D"})
                    </div>
                    <div>
                        @Html.LabelFor(x => x.Password, new {@class = "sr-only"})
                        @Html.PasswordFor(x => x.Password, new {id = "inputPassword", @class = "form-control", placeholder = "Password"})
                        @Html.ValidationMessageFor(x => x.Password, null, new {id = "l-Style", style = "color:#FF1C4D"})
                    </div>
                    <div>
                        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Submit"/>
                    </div>
                </div>
            }
            <p class="text-muted text-center">email: demo@demo.com password: pass</p>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/Content/JS/ResponsiveValidation.js"></script>
}

Views/Home/RegistrationForm.cshtml
@model Mandee.Models.RegModel

<div class="container">
    <div class="row pb-5">
        <div class="col">
            @using (Html.BeginForm())
            {
                <div class="form-signin">
                    <h2 class="form-signin-heading"  id="anchor">Register</h2>
                    <div>
                        @Html.LabelFor(x => x.Name, new {@class = "sr-only"})
                        @Html.TextBoxFor(x => x.Name, new {id = "inputName", @class = "form-control", placeholder = "Name"})
                        @Html.ValidationMessageFor(x => x.Name, null, new {id = "l-Style", style = "color:#FF1C4D"})
                    </div>
                    <div>
                        @Html.LabelFor(x => x.Address, new {@class = "sr-only"})
                        @Html.TextBoxFor(x => x.Address, new {id = "inputAddress", @class = "form-control", placeholder = "Address"})
                        @Html.ValidationMessageFor(x => x.Address, null, new {id = "l-Style", style = "color:#FF1C4D"})
                    </div>
                    <div>
                        @Html.LabelFor(x => x.Email, new {@class = "sr-only"})
                        @Html.TextBoxFor(x => x.Email, new {id = "inputEmail", @class = "form-control", placeholder = "Email"})
                        @Html.ValidationMessageFor(x => x.Email, null, new {id = "l-Style", style = "color:#FF1C4D"})
                    </div>
                    <div>
                        @Html.LabelFor(x => x.Phone, new {@class = "sr-only"})
                        @Html.TextBoxFor(x => x.Phone, new {id = "inputPhone", @class = "form-control", placeholder = "Phone number"})
                        @Html.ValidationMessageFor(x => x.Phone, null, new {id = "l-Style", style = "color:#FF1C4D"})
                    </div>
                    <div>
                        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Submit"/>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/Content/JS/ResponsiveValidation.js"></script>
}

Views/Home/Secure.cshtml
<div class="container">
    <div class="row">
        <div class="col">
            <h2 id="anchor">Secure section</h2>
        </div>
    </div>
    <div class="row" id="anchor">
        <div class="col pb-5">
            <p>Hello from your secure area</p>
            <p>Below is a link to the git repo of this site. If you'd link access send me a quick email.</p>
            <a href="https://fused19@bitbucket.org/fused19/recruitmentsitedemo.git">Git repo</a>
        </div>
    </div>
</div>